if(!"Unicode" %in% .packages(TRUE))install.packages("Unicode")
if(!"RODBC" %in% .packages(TRUE))install.packages("RODBC")
if(!"zoo" %in% .packages(TRUE))install.packages("zoo")
if(!"gplots" %in% .packages(TRUE))install.packages("gplots")
if(!"caTools" %in% .packages(TRUE))install.packages("caTools")
if(!"dplyr" %in% .packages(TRUE))install.packages("dplyr")
if(!"multcomp" %in% .packages(TRUE))install.packages("multcomp")
if(!"devtools" %in% .packages(TRUE))install.packages("devtools")
library(devtools)
if(!"ggplot2" %in% .packages(TRUE))install.packages("ggplot2")
if(!"plyr" %in% .packages(TRUE))install.packages("plyr")
if(!"reshape2" %in% .packages(TRUE))install.packages("reshape2")
if(!"Hmisc" %in% .packages(TRUE))install.packages("Hmisc")
if(!"gridExtra" %in% .packages(TRUE))install.packages("gridExtra")
if(!"grid" %in% .packages(TRUE))install.packages("grid")
if(!"lubridate" %in% .packages(TRUE))install.packages("lubridate")
if(!"doBy" %in% .packages(TRUE))install.packages("doBy")
if(!"R2wd" %in% .packages(TRUE))install.packages("R2wd")
if(!"RDCOMClient" %in% .packages(TRUE))install.packages("RDCOMClient")
if(!"multcompView" %in% .packages(TRUE))install.packages("multcompView")
if(!"nlme" %in% .packages(TRUE))install.packages("nlme")
if(!"car" %in% .packages(TRUE))install.packages("car")
if(!"corrplot" %in% .packages(TRUE))install.packages("corrplot")
if(!"nlrwr" %in% .packages(TRUE))install.packages("nlrwr")
if(!"sciplot" %in% .packages(TRUE))install.packages("sciplot")
if(!"nlstools" %in% .packages(TRUE))install.packages("nlstools")
if(!"seqinr" %in% .packages(TRUE))install.packages("seqinr")
if(!"plotBy" %in% .packages(TRUE))install_bitbucket("plotBy", "remkoduursma")
if(!"gplots" %in% .packages(TRUE))install.packages("gplots")
if(!"broom" %in% .packages(TRUE))install_github("broom", "dgrtwo")### to collect tiny out put of model
#install Remko's package, includes the functions fitaci() and fitacis(). Just run ONCE.
if(!"plantecophys" %in% .packages(TRUE))install_bitbucket(repo="plantecophys",username="remkoduursma")
if(!"propagate" %in% .packages(TRUE))install.packages("propagate")
if(!"lme4" %in% .packages(TRUE))install.packages("lme4")
if(!"lmerTest" %in% .packages(TRUE))install.packages("lmerTest")
if(!"smatr" %in% .packages(TRUE))install.packages("smatr")
if(!"readlicor" %in% .packages(TRUE))install_bitbucket("readlicor","remkoduursma")
if(!"Rcpp" %in% .packages(TRUE))install.packages("Rcpp")

